<script setup lang="ts">
const config = useRuntimeConfig()
const { data: places } = await useFetch<any[]>(`${config.public.apiBase}/places`, { default: () => [] })
const { data: content } = await useFetch<any>(`${config.public.apiBase}/content/home`, { default: () => ({ data: {} }) })
const fallback = { navigation: { brand: 'Lao Tour' }, hero: { eyebrow: 'Discover Laos, slowly', title: 'Start your unforgettable', emphasis: 'journey with us.', description: 'From quiet rivers and golden temples to mountain paths — find the Laos that feels personal.', button: 'Explore now', image: 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=2400&q=90' }, search: { destination: 'Destination', style: 'Travel style', when: 'When', destinationValue: 'Explore Laos', styleValue: 'Any experience', whenValue: 'Any time of year' }, destinations: { eyebrow: 'Go somewhere meaningful', title: 'Popular destinations', description: 'Most popular destinations around Laos, from ancient capitals and hidden waterfalls to beautiful natural wonders.' }, offers: { eyebrow: 'Thoughtfully curated', title: 'Special offers', description: 'A carefully designed escape with local stays, memorable routes, and time to simply be.', button: 'DETAILS', from: 'From' }, journal: { eyebrow: 'Our travel journal', title: 'Beautiful Laos.\nLet’s travel slowly.', description: 'The best discoveries are rarely rushed. Follow the river, stop for market coffee, take the mountain road and let a place reveal itself in its own time.', button: 'Read more →', image: 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1300&q=85' }, gallery: { eyebrow: 'Through a different lens', title: 'Destination gallery' }, experiences: { eyebrow: 'Real stories, real journeys', title: 'Traveller’s experiences', quotes: ['Every detail felt considered, but the journey still had space to surprise us.', 'Our favourite days were the unplanned ones — coffee, quiet views and kind people.', 'A beautiful way to experience Laos beyond the usual itinerary.'] }, newsletter: { eyebrow: 'Stay inspired', title: 'Our newsletter', description: 'Stories and thoughtful travel notes, occasionally.', placeholder: 'Enter your email', button: 'Subscribe' } }
const home = computed(() => ({ ...fallback, ...(content.value?.data || {}) }))
const destinationsEl = ref<HTMLElement>()
function scrollDestinations(direction: number) { destinationsEl.value?.scrollBy({ left: direction * 360, behavior: 'smooth' }) }
const gallery = [
  'https://images.unsplash.com/photo-1529154036614-a60975f5c760?auto=format&fit=crop&w=700&q=85',
  'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=700&q=85',
  'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=700&q=85',
  'https://images.unsplash.com/photo-1504150558240-0b4fd8946624?auto=format&fit=crop&w=700&q=85'
]
</script>
<template>
  <div class="overflow-hidden bg-white">
    <section class="relative min-h-[660px] bg-[#173a2b] pt-20 text-white lg:min-h-[720px]">
      <img :src="home.hero.image" alt="Tropical Laos landscape" class="absolute inset-0 h-full w-full object-cover opacity-70"/><div class="absolute inset-0 bg-gradient-to-r from-[#0d2b21]/95 via-[#173a2b]/65 to-transparent"/>
      <div class="relative mx-auto max-w-7xl px-5 pt-28 lg:px-8 lg:pt-40"><p class="text-xs font-bold uppercase tracking-[.28em] text-[#f0d982]">{{ home.hero.eyebrow }}</p><h1 class="mt-5 max-w-3xl font-display text-5xl leading-[.98] sm:text-7xl lg:text-8xl">{{ home.hero.title }} <em class="text-[#f0d982]">{{ home.hero.emphasis }}</em></h1><p class="mt-6 max-w-xl text-lg leading-8 text-white/80">{{ home.hero.description }}</p></div>
      <form class="relative mx-auto mt-16 grid max-w-7xl gap-4 bg-white p-5 text-[#17261f] shadow-2xl md:grid-cols-4 lg:translate-y-10 lg:rounded-2xl lg:p-6" @submit.prevent><label class="search-field">{{ home.search.destination }}<select><option>{{ home.search.destinationValue }}</option><option>Luang Prabang</option><option>Vientiane</option></select></label><label class="search-field">{{ home.search.style }}<select><option>{{ home.search.styleValue }}</option><option>Nature</option><option>Culture</option><option>Adventure</option></select></label><label class="search-field">{{ home.search.when }}<select><option>{{ home.search.whenValue }}</option><option>Dry season</option><option>Green season</option></select></label><button class="rounded-xl bg-[#e57a5e] px-6 py-4 font-display text-xl text-white transition hover:bg-[#d76447]">{{ home.hero.button }}</button></form>
    </section>

    <section id="discover" class="mx-auto max-w-7xl px-5 py-24 lg:px-8 lg:pt-36"><div class="section-heading"><div><p>{{ home.destinations.eyebrow }}</p><h2>{{ home.destinations.title }}</h2><span/></div><div class="flex gap-2"><button class="arrow-button" aria-label="Previous destinations" @click="scrollDestinations(-1)">←</button><button class="arrow-button" aria-label="Next destinations" @click="scrollDestinations(1)">→</button></div></div><p class="section-intro">{{ home.destinations.description }}</p><div ref="destinationsEl" class="destination-slider mt-9"><NuxtLink v-for="place in places" :key="place.id" :to="`/places/${place.slug}`" class="group relative h-[360px] min-w-[280px] overflow-hidden rounded-2xl sm:min-w-[340px]"><img :src="place.image" :alt="place.title" class="h-full w-full object-cover transition duration-700 group-hover:scale-110"/><div class="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent"/><div class="absolute bottom-0 p-5 text-white"><h3 class="font-display text-3xl">{{ place.title }}</h3><p class="mt-1 text-sm text-white/75"><UIcon name="i-lucide-map-pin"/> {{ place.province }}</p></div></NuxtLink></div></section>

    <section class="mx-auto max-w-7xl px-5 py-12 lg:px-8"><div class="section-heading"><div><p>{{ home.offers.eyebrow }}</p><h2>{{ home.offers.title }}</h2><span/></div><button class="arrow-button">→</button></div><div class="mt-9 grid gap-5 md:grid-cols-3"><article v-for="(place, index) in places" :key="`offer-${place.id}`" class="overflow-hidden rounded-2xl border border-[#eeeae4] bg-white"><img :src="place.image" :alt="place.title" class="h-44 w-full object-cover"/><div class="p-5"><h3 class="font-display text-2xl">{{ place.province }}</h3><p class="mt-2 text-[#f3b127]">★★★★★</p><p class="mt-2 text-sm leading-6 text-[#66736d]">{{ home.offers.description }}</p><div class="mt-4 flex items-end justify-between"><p class="text-sm text-[#66736d]">{{ home.offers.from }} <b class="ml-1 text-2xl text-[#e57a5e]">${{ 480 + index * 140 }}</b></p><NuxtLink :to="`/places/${place.slug}`" class="rounded-lg bg-[#e57a5e] px-3 py-2 text-xs font-bold text-white">{{ home.offers.button }}</NuxtLink></div></div></article></div></section>

    <section id="about" class="mx-auto grid max-w-7xl gap-10 px-5 py-28 lg:grid-cols-2 lg:px-8"><img :src="home.journal.image" alt="Misty Laos mountains" class="h-[430px] w-full rounded-2xl object-cover"/><div class="self-center"><p class="eyebrow">{{ home.journal.eyebrow }}</p><h2 class="mt-3 whitespace-pre-line font-display text-5xl leading-tight text-[#283f48]">{{ home.journal.title }}</h2><p class="mt-6 max-w-lg leading-8 text-[#5c6a68]">{{ home.journal.description }}</p><NuxtLink to="/#discover" class="mt-7 inline-block font-semibold text-[#e57a5e]">{{ home.journal.button }}</NuxtLink></div></section>

    <section id="journeys" class="bg-[#f7f7f4] py-24"><div class="mx-auto max-w-7xl px-5 lg:px-8"><div class="section-heading"><div><p>{{ home.gallery.eyebrow }}</p><h2>{{ home.gallery.title }}</h2><span/></div><button class="arrow-button">→</button></div><div class="mt-9 grid grid-cols-2 gap-4 md:grid-cols-4"><img v-for="(image, index) in gallery" :key="image" :src="image" :alt="`Laos gallery image ${index + 1}`" class="h-52 w-full rounded-xl object-cover md:h-72"/></div></div></section>

    <section class="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div class="section-heading"><div><p>{{ home.experiences.eyebrow }}</p><h2>{{ home.experiences.title }}</h2><span/></div></div><div class="mt-10 grid gap-5 md:grid-cols-3"><article v-for="(quote, index) in home.experiences.quotes" :key="quote" class="rounded-2xl bg-[#f7f7f4] p-6"><div class="flex items-center gap-3"><span class="grid h-10 w-10 place-items-center rounded-full bg-[#d9e6dd] font-display text-[#173a2b]">{{ ['M','K','S'][index] }}</span><div><p class="font-semibold">{{ ['Mina K.', 'Kamal & Nia', 'Sophie T.'][index] }}</p><p class="text-xs text-[#7b8983]">Travel guest</p></div></div><p class="mt-5 text-[#f3b127]">★★★★★</p><p class="mt-3 leading-7 text-[#52635d]">“{{ quote }}”</p></article></div></section>

    <section class="mx-auto max-w-4xl px-5 pb-20"><div class="rounded-2xl bg-[#173a2b] p-8 text-white md:flex md:items-center md:justify-between md:p-10"><div><p class="eyebrow text-[#f0d982]">{{ home.newsletter.eyebrow }}</p><h2 class="mt-2 font-display text-4xl">{{ home.newsletter.title }}</h2><p class="mt-2 text-white/70">{{ home.newsletter.description }}</p></div><form class="mt-5 flex gap-2 md:mt-0"><input type="email" :placeholder="home.newsletter.placeholder" class="min-w-0 rounded-lg bg-white px-4 py-3 text-[#17261f] outline-none"/><button class="rounded-lg bg-[#e57a5e] px-4 py-3 font-semibold">{{ home.newsletter.button }}</button></form></div></section>
  </div>
</template>

<style scoped>
.section-heading{display:flex;align-items:end;justify-content:space-between}.section-heading p,.eyebrow{font-size:.7rem;font-weight:700;letter-spacing:.16em;text-transform:uppercase;color:#a47c4d}.section-heading h2{margin-top:.6rem;font-family:var(--font-serif);font-size:2.7rem;line-height:1;color:#283f48}.section-heading span{display:block;margin-top:.8rem;height:2px;width:4rem;background:#e57a5e}.section-intro{margin-top:1.1rem;color:#78817e;font-size:.9rem}.arrow-button{display:grid;height:2.25rem;width:2.25rem;place-items:center;border-radius:.45rem;background:#173a2b;color:white;transition:.2s}.arrow-button:hover{background:#e57a5e}.search-field{display:flex;flex-direction:column;gap:.45rem;font-size:.65rem;font-weight:700;letter-spacing:.1em;text-transform:uppercase;color:#82918b}.search-field select{border-bottom:1px solid #d9dfd9;background:transparent;padding:0 0 .5rem;color:#283f48;font-size:.875rem;font-weight:500;letter-spacing:0;text-transform:none;outline:none}
.destination-slider{display:flex;gap:1rem;overflow-x:auto;scroll-snap-type:x mandatory;padding-bottom:.5rem;scrollbar-width:none}.destination-slider::-webkit-scrollbar{display:none}.destination-slider>*{scroll-snap-align:start}
</style>
